spring:
  application:
    name: order

  data:
    mongodb:
      host: localhost
      port: 27017
      database: ecommerce

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_URL}

kafka:
  url: ${KAFKA_URL}
  topic: notification-topic

server:
  port: 8081